# Permalinks
permalink:      /:year/:month/:day/:title

# Setup
title:          AI-Ops
author:         UnionPay AI-Ops Lab
description:    中国银联信息总中心智能化运维技术交流分享平台
paginate:       15
baseurl:         ""
url:             "http://ai-ops.up082.cn"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# Gems
plugins:
  - jekyll-paginate

# Format
highlighter: rouge
#highlighter: pygments

# Social
social:
    weibo: yougzhao
    github: yougzhao
    mail: yougzhao@gmail.com
